# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0025_auto_20180730_2038'),
        ('data', '0016_auto_20181003_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPublicRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grout.Record')),
                ('speed', models.BooleanField()),
                ('lights', models.BooleanField()),
                ('direction', models.CharField(choices=[(b'centerbound', b'center'), (b'outerbound', b'outer')], max_length=20)),
                ('comments', models.CharField(max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('grout.record',),
        ),
        migrations.RemoveField(
            model_name='recordauditlogentry',
            name='log',
        ),
        migrations.RemoveField(
            model_name='recordauditlogentry',
            name='signature',
        ),
        migrations.AlterField(
            model_name='recordauditlogentry',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grout.Record'),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='duplicate_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_record', to='grout.Record'),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='grout.Record'),
        ),
    ]
