# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20190215_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpublicrecord',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='driverpublicrecord',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='driverpublicrecord',
            name='lights',
        ),
        migrations.RemoveField(
            model_name='driverpublicrecord',
            name='speed',
        ),
    ]
