# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0018_auto_20190216_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRecordAuditLogEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('record_uuid', models.CharField(db_index=True, max_length=36)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[(b'create', b'Create'), (b'update', b'Update'), (b'delete', b'Delete')], max_length=6)),
                ('log', models.TextField(null=True)),
                ('signature', models.CharField(max_length=36, null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.DriverPublicRecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recordauditlogentry',
            name='log',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recordauditlogentry',
            name='signature',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='recordauditlogentry',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.DriverRecord'),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='duplicate_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_record', to='data.DriverRecord'),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='data.DriverRecord'),
        ),
    ]
