---

# Installs packages/dependencies for web servers

#- hosts: all

#  pre_tasks:
#    - name: Gather EC2 facts
#      action: ec2_facts
#      when: staging

- hosts: celery-servers

  become: True

  vars:
    celery: True

  pre_tasks:
    - name: Add Docker APT key via curl proxied
      shell: "export HTTPS_PROXY=172.20.1.1:8888; curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"


    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "driver.python2" }
    - { role: "driver.celery" }
    - { role: "driver-celery.nginx" }
    - { role: "driver.r-docker" }
#    - { role: "driver.gradle" }
  environment:
    http_proxy: http://172.20.1.1:8888
    https_proxy: https://172.20.1.1:8888

